name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  gradle:
    name: Compile bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew bundle
  detekt:
    runs-on: ubuntu-latest
    name: Check kotlin code quality and formatting in ${{ matrix.dir }}
    strategy:
      fail-fast: false
      matrix:
        dir:
          - shared
          - server
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    permissions:
      security-events: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run detekt
        run: cd ${{ matrix.dir }} && ../gradlew detekt
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v1
        if: success() || failure()
        with:
          sarif_file: ${{ matrix.dir }}/build/reports/detekt/detekt.sarif
          category: detekt-${{ matrix.dir }}
  prettier:
    runs-on: ubuntu-latest
    name: Run prettier for frontend
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Check prettiness
        uses: creyD/prettier_action@v4.2
        with:
          dry: True
          prettier_options: "--no-error-on-unmatched-pattern --check client/**/*.{js,jsx,ts,tsx,vue,css,scss,html,md,json,yml}"
